import com.github.aliakseikaraliou.eloabff.data.TeamsByParser
import java.io.FileWriter
import org.apache.commons.csv.CSVFormat
import org.apache.commons.csv.CSVPrinter


/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
fun parseAndSave(url: String, file: String) {
    val matches = TeamsByParser(
            url = url)
            .parse()

    val fileWriter = FileWriter("csv/$file")
    CSVPrinter(fileWriter, CSVFormat.DEFAULT.withHeader("date", "team1", "team2", "score1", "score2"))
            .use { printer ->
                matches.forEach { match ->
                    printer.printRecord(match.date, match.team1, match.team2, match.score1, match.score2)
                }
            }
}

fun main() {
    parseAndSave("http://www.teams.by/raspisanie-matchey-pervaya-league-1997-chempionat-belarusi/calendar-2453/",
            "2019.csv")
}
